package it.org.agilos.zendesk_jira_plugin.integrationtest;

import java.net.URL;

import javax.xml.ws.WebServiceException;

import net.sourceforge.jwebunit.junit.WebTester;
import net.sourceforge.jwebunit.util.TestingEngineRegistry;

import org.agilos.jira.soapclient.JiraSoapService;
import org.agilos.jira.soapclient.JiraSoapServiceService;
import org.agilos.jira.soapclient.JiraSoapServiceServiceLocator;
import org.apache.log4j.Logger;

/**
 * Wraps the implementation details of how to connect to JIRA and login.
 * 
 * This is a Singleton, so use the  {@link #instance} method to get an instance to the concrete instance.
 * 
 * The following system properties define the behavior of the <code>JIRAClient</code>:
 * <ul>
 * <li> zendesk.jira.url The url of the JIRA instance the client should connect to
 * <li> zendesk.jira.login.name The Username to login with
 * <li> zendesk.jira.login.password The password to login to jira with
 * </ul>
 */
public class JIRAClient {
	private static JIRAClient instance = new JIRAClient();

	protected JiraSoapService jiraSoapService;
	protected String jiraSoapToken;

	public static String jiraUrl;
	public static String loginName = System.getProperty("zendesk.jira.login.name", "bamboo");
	public static String loginPassword = System.getProperty("zendesk.jira.login.password","bamboo2997");

	private Logger log = Logger.getLogger(JIRAClient.class.getName());

	private WebTester webTester;
	
	private static LocalTestEnvironmentData testEnvironmenData;

	private JIRAClient() {
		// Override default loading of localtest.properties by LocalTestEnvironment as this is autogenerated by the Atlassian PDK
		if (System.getProperty("test.server.properties") == null || System.getProperty("test.server.properties").equals("")) 
			System.setProperty("test.server.properties", "test-jira-4.0.properties");
		
		testEnvironmenData = new LocalTestEnvironmentData();
		jiraUrl = testEnvironmenData.getBaseUrl().toString();
		initWebTester();


	}

	public LocalTestEnvironmentData getTestEnvironmentData() {
		return testEnvironmenData;
	}

	public void login() throws Exception {		
		login(loginName, loginPassword);
	}

	public void login(String user, String password) throws Exception {
		loginToWS(user, password);

		loginToGUI(user, password);
	}

	private void loginToWS(String user, String password) throws Exception {
		URL jiraSOAPServiceUrl = new URL(jiraUrl+"/rpc/soap/jirasoapservice-v2");
		JiraSoapServiceService jiraSoapServiceGetter = new JiraSoapServiceServiceLocator();
		log.debug("Retriving jira soap service from "+jiraSOAPServiceUrl);
		jiraSoapService = jiraSoapServiceGetter.getJirasoapserviceV2(jiraSOAPServiceUrl);
		log.debug("Logging in with user: "+user+" and password: "+password);
		jiraSoapToken = jiraSoapService.login(user, password);
	}

	public WebTester getWebTester() {
		return webTester;
	}

	public static JIRAClient instance() throws WebServiceException {
		return instance;
	}

	/**
	 * Returns the JIRA service instance the client uses to connect to JIRA.
	 */
	public JiraSoapService getService() {
		if (jiraSoapService == null) throw new WebServiceException("Haven't been able to connect to the JIRA server, see log for further details");
		return jiraSoapService;
	}

	/**
	 * The login token needed in all SOAP calls to JIRA
	 */
	public String getToken() {
		if (jiraSoapToken == null) throw new WebServiceException("Haven't been able to login to the JIRA server, see log for further details");
		return jiraSoapToken;
	}

	private void initWebTester() { 
		webTester = new WebTester();
		webTester.setTestingEngineKey(TestingEngineRegistry.TESTING_ENGINE_HTMLUNIT);
		webTester.setBaseUrl(jiraUrl);
		webTester.setScriptingEnabled(true);
		webTester.beginAt("");
	}

	public void loginToGUI(String username, String password) {
		webTester.gotoPage("secure/Dashboard.jspa");
		webTester.setTextField("os_username", username);
		webTester.setTextField("os_password", password);
		webTester.clickButton("login");
	}

	public void setZendeskUrl(String zendeskURL) {
		gotoListenerConfiguration();
		log.info("Updating Zendesk URL to "+zendeskURL);
		getWebTester().setTextField("ZendeskUrl", zendeskURL);
		getWebTester().clickButton("Update");
		getWebTester().assertTextPresent(zendeskURL);
	}

	public void setZendeskCredentials(String zendeskLogin, String zendeskPW) {
		gotoListenerConfiguration();
		log.info("Updating Zendesk log to "+zendeskLogin+" and zendesk PW to "+zendeskPW);
		getWebTester().setTextField("LoginName", zendeskLogin);
		getWebTester().setTextField("LoginPassword", zendeskPW);
		getWebTester().clickButton("Update");
		getWebTester().assertTextPresent(zendeskLogin);
		getWebTester().assertTextPresent(zendeskPW);
	}

	public void setCommentsPublic(String publicComments) {
		gotoListenerConfiguration();
		log.info("Setting public comment value to "+publicComments);
		getWebTester().setTextField("Public comments", publicComments);
		getWebTester().clickButton("Update");
		getWebTester().assertTextPresent(publicComments);
	}	

	private void gotoListenerConfiguration() {
		gotoAdmin();
		gotoAdminSection("listeners");
		getWebTester().clickLink("");
		getWebTester().clickLinkWithText("Edit");
		getWebTester().assertTextPresent("ZendeskUrl");
	}

	public void setUploadAttachments(String uploadAttachments) {
		gotoListenerConfiguration();
		log.info("Updating updateAttachments to "+uploadAttachments);
		getWebTester().setTextField("Upload attachments", uploadAttachments);
		getWebTester().clickButton("Update");
		getWebTester().assertTextPresent(uploadAttachments);
	}

	public void gotoAdmin()	{
		webTester.clickLink("admin_link");
	}

	public void gotoAdminSection(String linkId) {
		gotoAdmin();
		webTester.clickLink(linkId);
	}
}
